dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  default: development
  development:
    verify: false
    gasreserve: 30000
  mainnet-fork-ganache:
    verify: false
    gasreserve: 30000
  goerli:
    verify: true
    gasreserve: 4094700000000000